"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[env_var.KUBECONFIG]
default = ""
detect_env_vars = ['KUBECONFIG']
format = ""
#format = "debugK: [$env_value]($style) "


[custom.kubeconfig_basename]
command = "echo ${KUBECONFIG##*/} | sed 's/\\.cfg$//'"
when = 'test -n "$KUBECONFIG"'
format = "[☸$output]($style) "
style = "green"

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[package]
disabled = true

[cmd_duration]
min_time = 5000
format = 'took [$duration](bold yellow)'

[aws]
disabled = true

[azure]
format = 'on [$symbol($subscription)]($style) '
disabled = true

[gcloud]
disabled = true

[directory]
truncate_to_repo = true
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[docker_context]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol]($style) [$context( \($namespace\))]($style) '
symbol = '☸'
detect_env_vars = [ 'KUBECONFIG' ]
[[kubernetes.contexts]]
context_pattern = ".*[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}"
context_alias = "🆔 "
style = "green"
[[kubernetes.contexts]]
context_pattern = "docker-desktop"
context_alias = "dd"

[git_branch]
ignore_branches = ['master', 'main']
format = " [$symbol$branch]($style) "
symbol = "🍣 "
style = "bold yellow"

[git_status]
conflicted = '🚩'
ahead = '🚅 x${count}'
behind = '🐢 x${count}'
diverged = '🔱🚅 x${ahead_count} 🐢 x${behind_count}'
up_to_date = ''
untracked = '🤷 x${count}'
stashed = '📦 x${count}'
modified = '📝 x${count}'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑x${count}'
disabled = false

[golang]
disabled = true

[nix_shell]
disabled = false
impure_msg = 'devbox'
format = 'via [$symbol$state](bold purple) '
symbol =  '☃️ '

[sudo]
disabled = false

[hostname]
ssh_only = true
format = '[$hostname](bold dimmed white) '
disabled = false
 
[username]
format = '[$user@]($style)'
disabled = true
show_always = false

[time]
disabled = false
time_format = "%R"
format = "⏰$time($style) "
style = "bright-white"
time_range = '16:40:00-17:20:00'

[nodejs]
format = "via [🤖 $version](bold green) "

